/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
  ],
  safelist: [
    'bg-dataAI',
    'bg-operations',
    'bg-product',
    'bg-ux',
    'bg-quality',
    'bg-cloud',
    'hover:bg-dataAI',
    'hover:bg-operations',
    'hover:bg-product',
    'hover:bg-ux',
    'hover:bg-quality',
    'hover:bg-cloud',
    'border-dataAI',
    'border-operations',
    'border-product',
    'border-ux',
    'border-quality',
    'border-cloud',
    'text-dataAI',
    'text-operations',
    'text-product',
    'text-ux',
    'text-quality',
    'text-cloud',
  ],
  theme: {
    extend: {
      colors: {
        color03_black: '#010B39',
        color02_blue: '#4361EE',
        dataAI: '#4CC9F0',
        operations: '#360B98',
        product: '#F2AC59',
        ux: '#7209B7',
        quality: '#43C773',
        cloud: '#F72585',
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
};
